apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    app: oc-apm
  labels:
    app: oc-apm
  name: oc-apm-role
  namespace: test-deployer
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - serviceaccounts
      - configmaps
      - persistentvolumeclaims
    verbs:
      - get
      - list
      - create
      - update
      - delete
  - apiGroups:
      - apps
    resources:
      - statefulsets
    verbs:
      - get
      - list
      - create
      - update
      - delete
  - apiGroups:
      - apps.openshift.io
    resources:
      - deploymentconfigs
    verbs:
      - get
      - list
      - create
      - update
      - delete
  - apiGroups:
      - route.openshift.io
    resources:
      - routes
    verbs:
      - get
      - list
      - create
      - update
      - delete
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - roles
      - rolebindings
    verbs:
      - get
      - list
      - create
      - update
      - delete
